### ISSUE TITLE
建议：文档可以再详细些，比如说可以加些架构设计，使用说明等。

### ISSUE THREAD

**Issue by jiangsuwwj1** [tigcode/jupiter#1]

**Comment by felixen** [comment]
@jiangsuwwj1  ok 后续逐步完善。

**Comment by felixen** [comment]
@jiangsuwwj1  如果您关注jupiter架构设计，可以关注微信公众号TIGCHAT ，在2017-05-10号有一篇文章《京东商城ContainerLB实践》，讲述的是实现的技术细节。谢谢。
